import pyautogui as gui
gui.confirm(text='deseja proceguir?', title="Guia", buttons=['Sim', 'Não'])
gui.press('win')
gui.write('google chrome')
gui.press('enter')
gui.moveTo(1432,381, duration=1)
gui.click()
gui.write('youtube.com')
gui.press('enter')
gui.moveTo(1377,131, duration=2)
gui.click()
gui.write('dor for love 2pac')
gui.press('enter')
gui.moveTo(1261,298, duration=1)
gui.click()
gui.moveTo(1804,20, duration=1)
gui.click()
gui.press('win')
gui.write('roblox player')
gui.press('enter')
gui.confirm(text='deu certo?', title="Guia", buttons=['Sim', 'Não'])
if gui.confirm(text='deu certo?', title="Guia", buttons=['Sim', 'Não']) == 'Sim':
    gui.confirm(text='gostou da experiência?', title="Guia", buttons=['Sim', 'Não'])
    gui.alert(text='obrigado por usar nosso sistema', title="Guia", button='OK')
    gui.alert(text='agora aproveite seu jogo😉👍', title="Guia", button='OK')
else:
    gui.alert(text='você fez algo de errado... tente novamente', title="Guia", button='OK')